version: "3.8"

services:
  web:
    image: nginx:alpine
    container_name: test-holamundo
    restart: unless-stopped
    networks:
      - vpn_net
    volumes:
      - ./html:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"

      # HTTP router (redirige a HTTPS)
      - "traefik.http.routers.test.entrypoints=http"
      - "traefik.http.routers.test.rule=Host(`edusnapec.online`)"
      - "traefik.http.middlewares.test-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.test.middlewares=test-https-redirect"

      # HTTPS router
      - "traefik.http.routers.test-secure.entrypoints=https"
      - "traefik.http.routers.test-secure.rule=Host(`edusnapec.online`)"
      - "traefik.http.routers.test-secure.tls=true"
      - "traefik.http.routers.test-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.test-secure.tls.domains[0].main=edusnapec.online"

      # Puerto interno del contenedor (ajusta si es diferente)
      - "traefik.http.services.test.loadbalancer.server.port=80"

networks:
  vpn_net:
    external: true
